channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.11

  - pip=20.2.1
  - pip:
    # Define pip packages here.
    # https://pypi.org/
    - rpaframework==28.6.1 # https://rpaframework.org/releasenotes.html
    - robocorp==2.1.0